### ISSUE TITLE
Not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by anshulnsit** [Parth-Vader/MobOff#8]
<pre>Traceback (most recent call last):
  File "/usr/local/bin/moboff", line 9, in <module>
    load_entry_point('MobOff==0.1', 'console_scripts', 'moboff')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'mainscript'
</pre>

**Comment by Parth-Vader** [comment]
Did you follow the instructions?

**Comment by anshulnsit** [comment]
Yes

**Comment by anshulnsit** [comment]
This error comes on <pre>moboff initialise</pre> command

**Comment by Parth-Vader** [comment]
Thanks for reporting. Please check the instructions again, I have updated them. 
Let me know if you face any problems again.
